apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: nginx-config
data:
  webservice.conf: |
   server {
     listen       80;
     server_name  localhost;
     location / {
       proxy_pass http://webservice.default:80/;
     }
   }


